name: Dispatch Event to Private Repo

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which environment to deploy to'
        required: true
        default: 'staging'

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Send repository_dispatch to private repo
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/<usuario>/<private-repo>/dispatches \
            -d '{"event_type": "deploy", "client_payload": {"environment": "${{ github.event.inputs.environment }}"}}'
