name: Deply environment
on:
  workflow_call:
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: "${{  github.event.inputs.environment }}"
    steps:
    
    - name: Entorno 
      run: |
        echo "El entorno a desplegar  ${{  github.event.inputs.environment }}"
        echo "API_URL=${{ vars.API_URL }}" 
        echo "LOG_LEVEL=${{ vars.LOG_LEVEL }}"

 
