name: Deply environment
on:
  workflow_call:
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: "${{  github.event.inputs.environment }}"
    steps:
    
    - name: Entorno 
      run: |
        echo "El entorno a desplegar  ${{  github.event.inputs.environment }}"

    - name: Cargar variables de entorno
      run: |
          echo "API_URL=${{ secrets.API_URL }}" >> $GITHUB_ENV
          echo "LOG_LEVEL=${{ secrets.LOG_LEVEL }}" >> $GITHUB_ENV
   
    
 
