name: Deply environment
on:
  workflow_call:
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: "${{  github.event.inputs.environment }}"
    steps:
    
    - name: Entorno 
      run: |
        echo "El entorno a desplegar  ${{  github.event.inputs.environment }}"

    - name: Verificar variables de entorno
      run: |
        if [ -z "${{ vars.API_URL }}" ]; then
          echo "La variable API_URL no está definida o está vacía."
        else
          echo "API_URL=${{ vars.API_URL }}"
        fi
        
        if [ -z "${{ vars.LOG_LEVEL }}" ]; then
          echo "La variable LOG_LEVEL no está definida o está vacía."
        else
          echo "LOG_LEVEL=${{ vars.LOG_LEVEL }}"
        fi
    
 
